# Generated by Django 5.1.4 on 2024-12-16 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='direktor',
            new_name='surname',
        ),
    ]
