# Generated by Django 5.1.4 on 2025-01-11 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_direktor_team_surname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='content',
            new_name='message',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='+998000000000', max_length=20),
        ),
    ]
