# Generated by Django 5.1.4 on 2025-01-11 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_rename_content_contact_message_contact_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(default='(+998)', max_length=20),
        ),
    ]
